language: node_js
sudo: false

node_js:
  - 0.8
  - '0.10'
  - 0.12
  - 4

before_install:
  - npm install -g npm@2
  - npm install -g npm

script:
  - npm run istanbul && cat ./coverage/lcov.info | coveralls
